### ISSUE TITLE
How to make folder contain subfolders contain images ?

### ISSUE THREAD

**Issue by Doan-Nguyen** [AlexiaJM/Deep-learning-with-cats#19]
first, i want to say thanks so much to Alexia. Now, t need make a folder contain subfolders save images, which be generated by DCGAN. I tried but not success. Help me.

**Comment by AlexiaJM** [comment]
Check out https://github.com/AlexiaJM/RelativisticGAN
It's a updated version with Relativistic GAN alternative losses and it contains a many extra functionalities, such as the one you want.

There are two arguments to generate, "gen_extra_images" and "gen_every". 

1) If your model is already trained and save to .pth, then use "load = /pathtopictures/state_10.pth" to restart from your model and use "gen_every"=1 and "gen_extra_images"=10000. Stop it as soon as its done with the folder of images because it wont stop generating folders of 10k images. 

2) To generate during training, for example: you can use "gen_every"=5000 and "gen_extra_images"=10000 to generate 10k images per 5k iterations in separate folders.
